#服务配置
server:
  #端口
  port: 8080
  #服务编码
  tomcat:
    uri-encoding: UTF-8
#spring相关配置
spring:
  #应用配置
  application:
    #服务名称
    name: dubbo-producer
  main:
    allow-bean-definition-overriding: true
  cloud:
    #nacos注册中心
    nacos:
      discovery:
        server-addr: 192.168.200.129:8848
dubbo:
  #dubbo服务版本
  application:
    version: 1.0.0
    logger: slf4j
  #dubbo接口扫描路径
  scan:
    base-packages: com.itheima.dubbo
  #dubbo服务注册
  registry:
    address: spring-cloud://192.168.200.129
  #dubbo服务协议类型及端口，线程数【这里是默认配置】
  protocol:
    name: dubbo
    port: 28080
    threads: 200
    accesslog: logs/dubbo-producer-01.log
    #服务提供方配置超时时间，默认是1s  1000ms
  provider:
    timeout: 2000
